services:
  diceduel:
    image: diceduel_game:latest
    container_name: diceduel_game
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - POSTGRES_CONNECTION_STRING=Host=postgres;Port=5432;Database=testdb;Username=root;Password=J28cg8R%CfGYAf
      - JWT_SECRET_KEY=MySuperSecretKeyWithAtLeast32Characters!
    restart: always
    ports:
      - 5000:80
    networks:
      - diceduel-network
    
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: J28cg8R%CfGYAf
      POSTGRES_DB: testdb
    volumes:
      - C:/volumes:/var/lib/postgresql/data
    networks:
      - diceduel-network

networks:
  diceduel-network: